name: Deployment
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
     - name: Delete deployment
       uses: strumwolf/delete-deployment-environment@v2
       with:
         token: ${{ secrets.GITHUB_TOKEN }}
         environment: github-pages
         onlyRemoveDeployments: true
